package com.example.entity;

public enum PaymentPurpose {
    DRIVER_REGISTRATION,
    TRANSPORTER_REGISTRATION,
    DRIVER_ADVANCE,
    TRANSPORTER_ADVANCE,
    MONTHLY_SETTLEMENT,
    DRIVER_TOPUP,
    MANUAL_TOPUP
}

