package com.example.entity;
public enum WalletTransactionPurpose {

    DRIVER_REGISTRATION,
    TRANSPORTER_REGISTRATION,

    DRIVER_ADVANCE,
    TRANSPORTER_ADVANCE,

    MONTHLY_SETTLEMENT,
    MANUAL_TOPUP,

    DRIVER_PAYOUT,
    TRANSPORTER_PAYOUT,

    ADMIN_ADJUSTMENT,
    PLATFORM_COMMISSION,
    INTEREST_CREDIT
}
